services:
  server:
    build:
      context: .
      target: development
    ports:
      - "8080:8080"
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wrm
      SPRING_DATASOURCE_USERNAME: axel
      SPRING_DATASOURCE_PASSWORD: 6631
    develop:
      watch:
        - action: rebuild
          path: .
  db:
    image: "postgres:latest"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=axel'
      - 'POSTGRES_DB=wrm'
      - 'POSTGRES_PASSWORD=6631'
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "wrm"]
      interval: 10s
      timeout: 5s
      retries: 5

#  pgadmin:
#    image: 'dpage/pgadmin4:latest'
#    environment:
#      PGADMIN_DEFAULT_EMAIL: axelyoucode@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#      PGADMIN_LISTEN_PORT: 5050
#    ports:
#      - '5050:5050'

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar

  sonarqube-db:
    image: postgres:13
    container_name: sonarqube-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar

volumes:
  db-data: