spring:
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:postgresql://localhost:5432/wrm
    username: axel
    password: 6631

  show-sql: true
  properties:
    hibernate:
      format_sql: true
